const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const reveals=$$('.reveal');const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('show')}),{threshold:.12});reveals.forEach(x=>io.observe(x));
addEventListener('scroll',()=>{const h=document.documentElement;$('.progress').style.width=((h.scrollTop/(h.scrollHeight-h.clientHeight))*100)+'%'});
$('#openGift').onclick=()=>{$('#welcome').classList.add('hide');burst(90)};
function burst(n=55){const box=$('#confetti');for(let i=0;i<n;i++){let p=document.createElement('i');p.className='confetti-piece';p.style.left=Math.random()*100+'vw';p.style.setProperty('--h',Math.random()*360);p.style.setProperty('--d',(2+Math.random()*3)+'s');p.style.setProperty('--x',(-120+Math.random()*240)+'px');box.append(p);setTimeout(()=>p.remove(),5200)}}
$('#confettiBtn').onclick=()=>burst();$('#finalCelebrate').onclick=()=>burst(100);
const target=new Date('2026-09-24T00:00:00');function tick(){let d=target-new Date();if(d<=0){$('#countTitle').textContent="It's Aunty's birthday! ♡";d=Math.abs(d)}let s=Math.floor(d/1000);$('#days').textContent=Math.floor(s/86400);$('#hours').textContent=Math.floor(s%86400/3600);$('#mins').textContent=Math.floor(s%3600/60);$('#secs').textContent=s%60}tick();setInterval(tick,1000);
const age=$('.age-number');const ageIO=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){let n=0;let t=setInterval(()=>{age.textContent=++n;if(n>=48)clearInterval(t)},35);ageIO.disconnect()}}));ageIO.observe(age);
const wishes=['May your year be filled with happy trips, good movies and lots of chocolate ♡','48 looks beautiful on you. Happy Birthday, Aunty!','More laughter, more jhumkas, more adventures, more memories ♡','Wishing you a year full of the people and places you love.'];let wi=0;$('#wishBtn').onclick=()=>{$('#wishText').textContent=wishes[wi++%wishes.length]};
$$('.fav').forEach(c=>c.onclick=()=>c.classList.toggle('active'));
const memories=[...$$('#gallery img')].map(x=>x.src);$('#memoryBtn').onclick=()=>{const im=$('#randomMemory');im.style.opacity=.2;setTimeout(()=>{im.src=memories[Math.floor(Math.random()*memories.length)];im.style.opacity=1},220)};
$$('.tilt').forEach(el=>{el.onmousemove=e=>{let r=el.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;el.style.transform=`perspective(700px) rotateY(${x*7}deg) rotateX(${-y*7}deg)`};el.onmouseleave=()=>el.style.transform=''});
$$('#gallery img').forEach(im=>im.onclick=()=>{$('#lightboxImg').src=im.src;$('#lightbox').classList.add('open')});$('#closeLightbox').onclick=()=>$('#lightbox').classList.remove('open');$('#lightbox').onclick=e=>{if(e.target.id==='lightbox')e.currentTarget.classList.remove('open')};
$('#candleBtn').onclick=()=>{$('#flame').classList.add('out');$('#candleMsg').textContent='Wish made ♡ Happy Birthday, Aunty!';burst(35)};
let hearts=0;$('#heartBtn').onclick=e=>{$('#heartCount').textContent=++hearts;let s=document.createElement('span');s.className='spark';s.textContent='♥';s.style.left=e.clientX+'px';s.style.top=e.clientY+'px';document.body.append(s);setTimeout(()=>s.remove(),700)};
addEventListener('pointermove',e=>{if(Math.random()>.92){let s=document.createElement('span');s.className='spark';s.textContent='✦';s.style.left=e.clientX+'px';s.style.top=e.clientY+'px';document.body.append(s);setTimeout(()=>s.remove(),700)}});
