const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const surprise=$('#surprise'); $('#openSurprise').onclick=()=>{surprise.classList.add('hidden'); burst(180); setTimeout(()=>surprise.remove(),900)};
function indiaNow(){return new Date(new Date().toLocaleString('en-US',{timeZone:'Asia/Kolkata'}))}
function pad(n){return String(n).padStart(2,'0')}
function tick(){const n=indiaNow(); $('#indiaTime').textContent=`${pad(n.getHours())}:${pad(n.getMinutes())}:${pad(n.getSeconds())}`; const start=new Date(n);start.setHours(0,0,0,0);let d=n-start;$('#birthdayElapsed').textContent=`${pad(Math.floor(d/3600000))}:${pad(Math.floor(d/60000)%60)}:${pad(Math.floor(d/1000)%60)}`}
tick();setInterval(tick,1000);
const wishes=['May your year be filled with new places and favorite people.','48 looks beautiful on you, Aunty.','More laughter, more travel, more family memories.','May every new adventure come with good food and great company.','Today calls for chocolate, halwa and a movie.'];let wi=0;
$('#wishBtn').onclick=()=>{let n=+(localStorage.auntyHearts||0)+1;localStorage.auntyHearts=n;$('#heartCount').textContent=`${n} heart${n===1?'':'s'}`;$('#wishText').textContent='“'+wishes[wi++%wishes.length]+'”';burst(25)};$('#heartCount').textContent=`${localStorage.auntyHearts||0} hearts`;
$$('.fav').forEach(b=>b.onclick=()=>{$$('.fav').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
const photos=$$('.photo-card'), lb=$('#lightbox'), lbi=$('#lightboxImg');let current=0;function openPhoto(i){current=(i+photos.length)%photos.length;lbi.src=photos[current].dataset.src;lb.classList.add('open')}photos.forEach((p,i)=>p.onclick=()=>openPhoto(i));$('#closeLightbox').onclick=()=>lb.classList.remove('open');$('#prevPhoto').onclick=()=>openPhoto(current-1);$('#nextPhoto').onclick=()=>openPhoto(current+1);lb.onclick=e=>{if(e.target===lb)lb.classList.remove('open')};document.addEventListener('keydown',e=>{if(e.key==='Escape')lb.classList.remove('open');if(lb.classList.contains('open')&&e.key==='ArrowRight')openPhoto(current+1);if(lb.classList.contains('open')&&e.key==='ArrowLeft')openPhoto(current-1)});
$('#randomMemory').onclick=()=>openPhoto(Math.floor(Math.random()*photos.length));$('#passport').onclick=()=>{$('#stamp').classList.add('show');burst(80)};$('#blow').onclick=()=>{$('#flame').classList.add('out');$('#cakeMsg').textContent='Wish made. Happy 48th, Aunty! ❤️';burst(100)};
['#celebrate','#finalCelebrate'].forEach(s=>$(s).onclick=()=>burst(160));
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.08});$$('.reveal').forEach(x=>io.observe(x));
addEventListener('scroll',()=>{$('#progress').style.width=(scrollY/(document.documentElement.scrollHeight-innerHeight)*100)+'%'});
const c=$('#confetti'),ctx=c.getContext('2d');let bits=[];function resize(){c.width=innerWidth;c.height=innerHeight}resize();addEventListener('resize',resize);function burst(n=100){for(let i=0;i<n;i++)bits.push({x:innerWidth*(.15+Math.random()*.7),y:innerHeight*.3,vx:(Math.random()-.5)*8,vy:-3-Math.random()*7,g:.12+Math.random()*.12,r:2+Math.random()*5,a:1,h:Math.random()*360})}function draw(){ctx.clearRect(0,0,c.width,c.height);bits=bits.filter(p=>p.a>0&&p.y<c.height+30);for(const p of bits){p.x+=p.vx;p.y+=p.vy;p.vy+=p.g;p.a-=.006;ctx.globalAlpha=p.a;ctx.fillStyle=`hsl(${p.h} 75% 58%)`;ctx.fillRect(p.x,p.y,p.r*1.7,p.r)}ctx.globalAlpha=1;requestAnimationFrame(draw)}draw();

// Birthday-year milestone countdowns, measured in India time.
const milestones=[['#count3','2026-12-24T00:00:00+05:30'],['#count6','2027-03-24T00:00:00+05:30'],['#count9','2027-06-24T00:00:00+05:30'],['#count12','2027-09-24T00:00:00+05:30']];
function milestoneTick(){const now=Date.now();milestones.forEach(([id,date])=>{let d=new Date(date)-now;if(d<=0){$(id).textContent='ARRIVED ✨';return}const days=Math.floor(d/86400000),hours=Math.floor(d/3600000)%24;$(id).textContent=`${days}d ${hours}h`})}milestoneTick();setInterval(milestoneTick,60000);
// Mumbai to SFO flight interaction.
const launch=$('#launchFlight'),plane=$('#travelPlane'),flightStatus=$('#flightStatus');
launch.onclick=()=>{plane.classList.remove('flying');void plane.offsetWidth;plane.classList.add('flying');launch.disabled=true;flightStatus.textContent='Taking off from Mumbai… ✈️';setTimeout(()=>flightStatus.textContent='Crossing oceans toward California… 🌏',1700);setTimeout(()=>flightStatus.textContent='Approaching San Francisco… 🌉',3500);setTimeout(()=>{flightStatus.textContent='Landed at SFO. Welcome to California, Aunty! ❤️';launch.disabled=false;burst(90)},5000)};
// Mobile-friendly 3x3 sliding photo puzzle.
const puzzle=$('#puzzle'),moveLabel=$('#puzzleMoves'),win=$('#puzzleWin');let board=[0,1,2,3,4,5,6,7,8],moves=0;
function renderPuzzle(){puzzle.innerHTML='';board.forEach((v,pos)=>{const b=document.createElement('button');b.className='puzzle-tile'+(v===8?' empty':'');b.setAttribute('aria-label',v===8?'Empty puzzle space':`Puzzle tile ${v+1}`);if(v!==8){const x=v%3,y=Math.floor(v/3);b.style.backgroundPosition=`${x*50}% ${y*50}%`}b.onclick=()=>moveTile(pos);puzzle.appendChild(b)});moveLabel.textContent=`${moves} move${moves===1?'':'s'}`}
function moveTile(pos){const empty=board.indexOf(8),a=[Math.floor(pos/3),pos%3],e=[Math.floor(empty/3),empty%3];if(Math.abs(a[0]-e[0])+Math.abs(a[1]-e[1])!==1)return;[board[pos],board[empty]]=[board[empty],board[pos]];moves++;renderPuzzle();if(board.every((v,i)=>v===i)){win.classList.add('show');burst(80)}}
function shufflePuzzle(){win.classList.remove('show');moves=0;for(let i=0;i<120;i++){const empty=board.indexOf(8),r=Math.floor(empty/3),c=empty%3,opts=[];if(r)opts.push(empty-3);if(r<2)opts.push(empty+3);if(c)opts.push(empty-1);if(c<2)opts.push(empty+1);const pos=opts[Math.floor(Math.random()*opts.length)];[board[pos],board[empty]]=[board[empty],board[pos]]}if(board.every((v,i)=>v===i))return shufflePuzzle();renderPuzzle()}
$('#shufflePuzzle').onclick=shufflePuzzle;shufflePuzzle();
